### PR TITLE
Added ForceSSL

### PR DESCRIPTION
**Pull request by m0byd1ck**
Added option to enable/disable HTTP to HTTPS redirection

### CODE REVIEW

**Comment by daverogers** [comment]
The spacing convention is tabs, could update your PR? Also, being a pretty sizable contribution, go ahead and add yourself as an @contributor in the PHPDoc :)

**Comment by m0byd1ck** [comment]
No problem, done.

**Comment by m0byd1ck** [comment]
Please can you tag this PR v1.0.2 so that it can be updated via composer?

**Comment by daverogers** [comment]
The last PR caused a conflict with yours, could you resolve that? Sorry for the inconvenience.

**Comment by acs-ferreira** [comment]
Any news on this? It is pretty useful!

**Comment by m0byd1ck** [comment]
Updated. Please review and set as 1.0.3 release.

**Comment by daverogers** [comment]
Thanks!

**Pull request merged**
